# Generated by Django 4.1 on 2022-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appEcoindustry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bonificacion", name="cantidad",),
        migrations.AddField(
            model_name="bonificacion",
            name="imagen",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
