# Generated by Django 4.0.6 on 2022-09-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEcoindustry', '0003_alter_puntos_usuarios_id_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('desComent', models.CharField(max_length=300)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEcoindustry.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAgenda', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEcoindustry.usuario')),
            ],
        ),
    ]
